name: CI
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v3.0.8
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with: 
          start: npx cypress open
        
